server:
  port: ${port:8502}

eureka:
  client:
    serviceUrl:
      defaultZone: ${eureka.serviceUrl:http://eureka.server:8501/eureka/}

spring:
  application:
    name: config-server
  cloud:
    config:
      label: master
      server:
        git:
          uri: https://git.oschina.net/qusthuang/xbin-store-cloud.git
          username: qusthuang
          password: 198812
          search-paths: config/*