spring:
  application:
    name: admin-dashboard

server:
  port: ${port:8505}

eureka:
  client:
    serviceUrl:
      defaultZone: ${eureka.serviceUrl:http://eureka.server:8501/eureka/}
  instance:
    hostname: ${hostname:admin}
    prefer-ip-address: true

---
spring:
  profiles: docker
  application:
    name: admin-dashboard

server:
  port: ${port:8505}

eureka:
  client:
    serviceUrl:
      defaultZone: ${eureka.serviceUrl:http://eureka.server:8501/eureka/}
  instance:
    hostname: ${hostname:admin}
    prefer-ip-address: true
